# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

RX_VERSION = '5.1.1'
ALAMOFIRE_VERSION = '4.9.1'
SWINJECT_VERSION = '2.7.1'
SWIFTLINT_VERSION = '0.35.0'
LIFETIMETRACKER_VERSION = '1.7.1'
IQKEYBOARDMANAGER_VERSION = '6.5.5'
SKELETON_VERSION = '1.9'
SNAPKIT_VERSION = '5.0.1'
SWIFTGEN_VERSION = '6.4.0'

def dependendcy
  pod 'RxSwift', RX_VERSION
  pod 'RxCocoa', RX_VERSION
  pod 'SwiftLint', SWIFTLINT_VERSION
  pod 'Alamofire', ALAMOFIRE_VERSION
  pod 'LifetimeTracker', LIFETIMETRACKER_VERSION
  pod 'Swinject', SWINJECT_VERSION
  pod 'IQKeyboardManagerSwift', IQKEYBOARDMANAGER_VERSION
  pod 'SkeletonView', SKELETON_VERSION
  pod 'SnapKit', SNAPKIT_VERSION
  pod 'SwiftGen', SWIFTGEN_VERSION
end

def test_dependendcy
  pod 'RxBlocking', RX_VERSION
  pod 'RxTest', RX_VERSION
end

target 'WeatherForecast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherForecast
  dependendcy
  
  target 'WeatherForecastTests' do
    inherit! :search_paths
    # Pods for testing
    test_dependendcy
  end

  target 'WeatherForecastUITests' do
    # Pods for testing
  end

end
